### ISSUE TITLE
Couldn't load messenger data

### ISSUE THREAD

**Issue by chintito4ever** [simonwongwong/Facebook-Messenger-Statistics#12]
Can you please tell me what am I missing here? 

C:\Users\User\Facebook-Messenger-Statistics>generate_report.py
Parsing data from D:/facebook/messages/inbox/ash_c6esfrteiq
Could not load messenger data
Exception caught: [WinError 267] The directory name is invalid: 'D:\\facebook\\messages\\inbox\\ashiqulhabib_c6esfrteiq\\message_1.json'

**Comment by simonwongwong** [comment]
try selecting just ` D:/facebook/messages/inbox` in the file dialog

**Comment by chintito4ever** [comment]
It worked, thank you so much. But looks like Facebook started splitting conversations into multiple files, for example message_1, message_2, but your program only includes message_1, so my question is, is there workaround for this?

**Comment by simonwongwong** [comment]
Thanks for letting me know, I pushed an update that should be able to read multiple `message_x.json` files now
