### ISSUE TITLE
Tag and word-length counts are not working. 

### ISSUE THREAD

**Issue by haganenoneko** [simonwongwong/Facebook-Messenger-Statistics#18]
The tag and word-length counts are either blank or the x-axes labels are missing/numeric. The definition of "from_chat" doesn't change during the call to "chat_stats," so I'm not sure why this problem is occurring, especially given that neither the tag- nor word-count functions were modified.

**Comment by simonwongwong** [comment]
did you manage to fix it? can you post your original comment again, I can take a look as well
