### ISSUE TITLE
Extract.py not behaving as expected

### ISSUE THREAD

**Issue by bickybilly** [simonwongwong/Facebook-Messenger-Statistics#5]
Not that I know exactly how the folders structure should turn out, but, I don't think this is it...

![image](https://user-images.githubusercontent.com/9663091/49245099-5c80c680-f3df-11e8-952c-35d0e767b6a2.png)

And all the folders not prefaced by "./archive" just have a "message.json" in them.
None of the JSONs were extracted out to the inbox folder (which is the folder in which I ran extract.py).

**Comment by bickybilly** [comment]
Ah, the issue is that Unix-based systems use "/" for path stuff, not "\\\\".

Got it to work by just changing those manually, but Python provides solutions that work for any OS: [see here](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f).

**Comment by simonwongwong** [comment]
Thanks, I have it working with pathlib on Windows, can you pull from master and check as well?

**Comment by simonwongwong** [comment]
Tested and working on Ubuntu
